template-file-path: infra/ecr-oidc.yaml
parameters:
  ECRRepositoryName: hello-app
  GitHubOrg: mahorobonheur
  ExistingOIDCProviderArn: arn:aws:iam::714377355835:oidc-provider/token.actions.githubusercontent.com
  Environment: lab
  GitHubRepo: push-docker-image-to-ecr-lab
tags: {}
